import { Shell } from '@/components/Shell'
import { WalletPreview } from '@/components/WalletPreview'
import { ArrowUpLeft, BadgeCheck, Building2, QrCode, Users, WalletCards } from 'lucide-react'
const stats = [['العملاء','1,284',Users],['الزيارات اليوم','187',QrCode],['المكافآت','42',BadgeCheck],['البراندات','3',Building2]] as const
export default function Admin(){return <Shell><div className="max-w-7xl mx-auto">
 <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-lime-300 text-sm">صباح الخير، أحمد</p><h1 className="text-3xl md:text-5xl font-black mt-2">نظرة عامة</h1></div><button className="bg-lime-300 text-black px-5 py-3 rounded-2xl font-bold flex items-center gap-2 w-fit">إضافة براند <ArrowUpLeft size={18}/></button></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-8">{stats.map(([label,value,Icon])=><div key={label} className="glass rounded-3xl p-5"><Icon className="text-white/40" size={20}/><div className="text-3xl font-black mt-5">{value}</div><div className="text-sm text-white/45 mt-1">{label}</div></div>)}</div>
 <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-5 mt-5"><section className="glass rounded-[30px] p-6"><div className="flex justify-between"><div><p className="text-white/45 text-sm">النشاط</p><h2 className="text-xl font-bold mt-1">آخر العمليات</h2></div><span className="text-lime-300 text-sm">عرض الكل</span></div><div className="mt-5 space-y-3">{['إضافة ختم إلى أحمد علي','استبدال مكافأة — فرع اللؤلؤة','تسجيل عميل جديد','تحديث تصميم بطاقة Bruno'].map((x,i)=><div key={x} className="flex justify-between items-center py-4 border-b border-white/5"><div><p className="font-medium">{x}</p><p className="text-xs text-white/35 mt-1">قبل {i+1} دقائق</p></div><span className="w-2 h-2 rounded-full bg-lime-300"/></div>)}</div></section>
 <section id="wallet" className="glass rounded-[30px] p-6"><div className="flex items-center gap-3"><WalletCards size={20}/><h2 className="text-xl font-bold">معاينة البطاقة</h2></div><div className="mt-5 scale-[.82] origin-top"><WalletPreview/></div></section></div>
 <div className="grid lg:grid-cols-2 gap-5 mt-5"><section className="glass rounded-[30px] p-6"><h2 className="text-xl font-bold">Apple Wallet</h2><p className="text-white/45 mt-2">ارفع شهادة Pass Type ID وسيتم فحصها قبل التفعيل.</p><div className="mt-5 border border-dashed border-white/20 rounded-3xl p-8 text-center"><p className="font-bold">اسحب ملف .p12 هنا</p><p className="text-xs text-white/35 mt-2">لن يتم عرض الشهادة للموظفين</p><button className="mt-5 px-5 py-3 rounded-2xl bg-white text-black font-bold">اختيار الشهادة</button></div></section><section className="glass rounded-[30px] p-6"><h2 className="text-xl font-bold">محرر التصميم</h2><div className="grid grid-cols-2 gap-3 mt-5">{['لون الخلفية','لون النص','الشعار','صورة الشريط','نص المكافأة','عدد الأختام'].map(x=><button key={x} className="rounded-2xl bg-white/5 border border-white/10 p-4 text-right hover:bg-white/10">{x}</button>)}</div><button className="w-full mt-4 bg-lime-300 text-black rounded-2xl py-4 font-bold">حفظ كنسخة جديدة</button></section></div>
 </div></Shell>}
