'use client'
import {useEffect,useState} from 'react'; import {Shell} from '@/components/Shell'; import {api} from '@/lib/api'; import {Building2,Users,ScanLine,Bell,Plus,Search,Gift,Send,RefreshCw} from 'lucide-react'
type Brand={id:string,name:string,slug:string}; type Customer={id:string,brand_id:string,name:string,phone:string,points:number,stamps:number,available_rewards:number,tier:string,membership_code:string,visits:number}
export default function Admin(){const [brands,setBrands]=useState<Brand[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[stats,setStats]=useState<any>({}),[brand,setBrand]=useState(''),[tab,setTab]=useState('overview'),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true)
 async function load(){setLoading(true);try{const [b,s]=await Promise.all([api('/api/brands'),api('/api/dashboard')]);setBrands(b);setStats(s);const id=brand||b[0]?.id||'';if(id){setBrand(id);setCustomers(await api(`/api/customers?brand_id=${id}`))}}catch(e:any){setMsg(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[])
 async function addBrand(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api('/api/brands',{method:'POST',body:JSON.stringify({name:f.get('name'),slug:f.get('slug'),primary_color:'#111827',accent_color:'#C6FF4A'})});e.currentTarget.reset();setMsg('تم إنشاء البراند');load()}
 async function addCustomer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api('/api/customers',{method:'POST',body:JSON.stringify({brand_id:brand,name:f.get('name'),phone:f.get('phone'),email:f.get('email')||null})});e.currentTarget.reset();setMsg('تم تسجيل العميل');setCustomers(await api(`/api/customers?brand_id=${brand}`))}
 async function adjust(c:Customer,p=10,s=1){await api(`/api/customers/${c.id}/loyalty`,{method:'POST',body:JSON.stringify({points:p,stamps:s,idempotency_key:crypto.randomUUID(),note:'Quick scan'})});setCustomers(await api(`/api/customers?brand_id=${brand}`));setMsg(`تم تحديث رصيد ${c.name}`)}
 async function notify(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d=await api('/api/notifications',{method:'POST',body:JSON.stringify({brand_id:brand,title:f.get('title'),body:f.get('body'),channel:f.get('channel'),audience:'all'})});setMsg(`تم إرسال الإشعار إلى ${d.recipients} عميل`);e.currentTarget.reset()}
 const cards=[[stats.customers||0,'العملاء',Users],[stats.transactions||0,'العمليات',ScanLine],[stats.notifications||0,'الإشعارات',Bell],[stats.brands||0,'البراندات',Building2]] as const
 return <Shell active={tab} onChange={setTab}><div className="max-w-7xl mx-auto"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-lime-300 text-sm">LOYALYN CONTROL CENTER</p><h1 className="text-4xl font-black mt-2">لوحة التحكم</h1></div><div className="flex gap-2"><select className="input min-w-48" value={brand} onChange={async e=>{setBrand(e.target.value);setCustomers(await api(`/api/customers?brand_id=${e.target.value}`))}}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="icon-btn" onClick={load}><RefreshCw size={18}/></button></div></div>{msg&&<div className="mt-5 rounded-2xl bg-lime-300/10 border border-lime-300/20 p-4 text-lime-200">{msg}</div>}
 {tab==='overview'&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-7">{cards.map(([n,l,I])=><div className="glass card" key={l}><I className="text-white/40"/><p className="text-3xl font-black mt-5">{n}</p><p className="text-white/45">{l}</p></div>)}</div><div className="grid lg:grid-cols-2 gap-5 mt-5"><section className="glass card"><h2>إنشاء براند جديد</h2><form onSubmit={addBrand} className="space-y-3 mt-5"><input name="name" required className="input" placeholder="اسم البراند"/><input name="slug" required pattern="[a-z0-9-]+" className="input" placeholder="brand-slug"/><button className="btn-primary"><Plus size={18}/> إنشاء البراند</button></form></section><section className="glass card"><h2>ملخص المنصة</h2><div className="space-y-4 mt-5 text-white/60"><p>إدارة مركزية للبراندات والفروع والعملاء.</p><p>نظام نقاط وأختام ومكافآت وسجل عمليات.</p><p>إشعارات فردية وجماعية مع دعم Webhook لمزود Push.</p><p>تجهيز Apple Wallet وربط الشهادات لاحقاً.</p></div></section></div></>}
 {tab==='customers'&&<><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-5 mt-7"><section className="glass card"><h2>تسجيل عميل</h2><form onSubmit={addCustomer} className="space-y-3 mt-5"><input name="name" required className="input" placeholder="اسم العميل"/><input name="phone" required className="input" placeholder="رقم الهاتف"/><input name="email" type="email" className="input" placeholder="البريد - اختياري"/><button className="btn-primary w-full"><Plus size={18}/> إضافة العميل</button></form></section><section className="glass card overflow-hidden"><div className="flex justify-between"><h2>العملاء</h2><span className="text-white/40">{customers.length}</span></div><div className="mt-4 space-y-2 max-h-[600px] overflow-auto">{customers.map(c=><div key={c.id} className="row"><div><b>{c.name}</b><p className="text-xs text-white/40 mt-1">{c.phone} · {c.tier} · {c.visits} زيارة</p></div><div className="flex items-center gap-3"><span className="text-sm">{c.points} نقطة · {c.stamps} ختم · {c.available_rewards} 🎁</span><button onClick={()=>adjust(c)} className="small-btn">+ زيارة</button></div></div>)}</div></section></div></>}
 {tab==='notifications'&&<div className="grid lg:grid-cols-2 gap-5 mt-7"><section className="glass card"><h2>إرسال إشعار جماعي</h2><form onSubmit={notify} className="space-y-3 mt-5"><input name="title" required className="input" placeholder="عنوان الإشعار"/><textarea name="body" required className="input min-h-32" placeholder="نص الرسالة"/><select name="channel" className="input"><option value="in_app">داخل المنصة</option><option value="push">Push Notification</option><option value="sms">SMS عبر مزود خارجي</option><option value="email">Email عبر مزود خارجي</option></select><button className="btn-primary"><Send size={18}/> إرسال لجميع العملاء</button></form></section><section className="glass card"><h2>كيف تعمل الإشعارات؟</h2><p className="text-white/50 leading-8 mt-5">يتم حفظ كل إشعار داخل صندوق العميل. وعند وضع رابط مزود الإشعارات في متغير <code>NOTIFICATION_WEBHOOK_URL</code> يرسل السيرفر نفس الرسالة إلى مزود Push أو SMS أو البريد دون تغيير المنصة.</p></section></div>}
 {tab==='wallet'&&<div className="glass card mt-7"><h2>Apple Wallet</h2><p className="text-white/50 mt-3">الهيكل والحقول جاهزة. التفعيل الحقيقي يحتاج Pass Type ID وTeam ID وشهادة Apple ‎.p12‎، ثم إضافة مولّد ملفات pkpass وخدمة تحديث البطاقة.</p><div className="wallet-card mt-8"><p className="text-sm opacity-60">LOYALYN MEMBER</p><h3 className="text-2xl font-black mt-4">بطاقة الولاء</h3><div className="flex justify-between mt-12"><span>النقاط<br/><b className="text-3xl">120</b></span><span>المكافآت<br/><b className="text-3xl">2</b></span></div></div></div>}
 {loading&&<p className="mt-8 text-white/40">جاري تحميل البيانات...</p>}</div></Shell>}
