'use client'
import {useEffect,useState} from 'react'
import {Shell} from '@/components/Shell'
import {api,API,token} from '@/lib/api'
import {Building2,Users,ScanLine,Bell,Plus,RefreshCw,Send,MapPin,UserCog,Star,Stamp,Gift,WalletCards,Copy,ExternalLink,Upload,ShieldCheck} from 'lucide-react'
type AnyRow=Record<string,any>
const Field=({name,placeholder,type='text',required=true,defaultValue}:{name:string,placeholder:string,type?:string,required?:boolean,defaultValue?:string|number})=><input name={name} required={required} type={type} defaultValue={defaultValue} className="input" placeholder={placeholder}/>
export default function Admin(){
 const [brands,setBrands]=useState<AnyRow[]>([]),[brand,setBrand]=useState(''),[tab,setTab]=useState('overview'),[stats,setStats]=useState<AnyRow>({}),[data,setData]=useState<Record<string,AnyRow[]>>({}),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false)
 const selected=brands.find(x=>x.id===brand)
 async function get(path:string){return await api(path)}
 async function loadCore(){setLoading(true);try{const [b,s]=await Promise.all([get('/api/brands'),get('/api/dashboard')]);setBrands(b);setStats(s);const id=brand||b[0]?.id||'';if(id){setBrand(id);await loadBrand(id)}}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 async function loadBrand(id=brand){if(!id)return;const paths:{[k:string]:string}={customers:`/api/customers?brand_id=${id}`,branches:`/api/manage/branches?brand_id=${id}`,employees:`/api/manage/employees?brand_id=${id}`,tiers:`/api/manage/tiers?brand_id=${id}`,rewards:`/api/manage/rewards?brand_id=${id}`,stamps:`/api/manage/stamp-programs?brand_id=${id}`,audit:`/api/manage/audit?brand_id=${id}`,certificates:`/api/manage/wallet/certificates?brand_id=${id}`};const pairs=await Promise.all(Object.entries(paths).map(async([k,p])=>[k,await get(p)]));setData(Object.fromEntries(pairs))}
 useEffect(()=>{loadCore()},[])
 async function submit(path:string,e:React.FormEvent<HTMLFormElement>,extra:AnyRow={},message='تم الحفظ'){e.preventDefault();const f=new FormData(e.currentTarget);const body:any={...Object.fromEntries(f.entries()),...extra};for(const k of Object.keys(body))if(body[k]==='')body[k]=null;for(const k of ['rank','min_points','min_spend','points_multiplier','points_cost','stock','required_stamps'])if(body[k]!==undefined&&body[k]!=='')body[k]=Number(body[k]);await api(path,{method:'POST',body:JSON.stringify(body)});e.currentTarget.reset();setMsg(message);await loadBrand()}
 async function addBrand(e:React.FormEvent<HTMLFormElement>){await submit('/api/brands',e,{primary_color:'#111827',accent_color:'#C6FF4A'},'تم إنشاء البراند وربط إعداداته') ;await loadCore()}
 async function adjust(c:AnyRow){await api(`/api/customers/${c.id}/loyalty`,{method:'POST',body:JSON.stringify({points:10,stamps:1,idempotency_key:crypto.randomUUID(),note:'زيارة سريعة'})});setMsg(`تمت إضافة زيارة إلى ${c.name}`);await loadBrand()}
 async function issue(c:AnyRow){const r=await api(`/api/manage/wallet/passes/${c.id}`,{method:'POST'});const url=`${location.origin}${r.card_url}`;await navigator.clipboard.writeText(url);setMsg('تم إصدار البطاقة ونسخ رابطها: '+url)}
 async function uploadCert(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);fd.set('brand_id',brand);const r=await fetch(`${API}/api/manage/wallet/certificates`,{method:'POST',headers:{Authorization:`Bearer ${token()}`},body:fd});const x=await r.json();if(!r.ok)throw new Error(x.detail||'فشل الرفع');setMsg('تم رفع الشهادة وحفظها في مساحة البراند');e.currentTarget.reset();await loadBrand()}
 const cards=[[stats.customers||0,'العملاء',Users],[stats.transactions||0,'العمليات',ScanLine],[stats.notifications||0,'الإشعارات',Bell],[stats.brands||0,'البراندات',Building2]] as const
 const rows=(key:string)=>data[key]||[]
 return <Shell active={tab} onChange={setTab}><div className="max-w-[1500px] mx-auto"><header className="topbar"><div><p className="eyebrow">LOYALYN CONTROL CENTER · V2</p><h1>{selected?.name||'إدارة المنصة'}</h1><p className="muted">كل البيانات والإعدادات معزولة ومربوطة بالبراند المحدد.</p></div><div className="flex gap-2"><select className="input min-w-52" value={brand} onChange={async e=>{setBrand(e.target.value);await loadBrand(e.target.value)}}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="icon-btn" onClick={loadCore}><RefreshCw size={18}/></button></div></header>{msg&&<div className="notice">{msg}<button onClick={()=>setMsg('')}>×</button></div>}
 {tab==='overview'&&<><div className="kpi-grid">{cards.map(([n,l,I])=><div className="glass kpi" key={l}><I/><div><strong>{n}</strong><span>{l}</span></div></div>)}</div><div className="grid lg:grid-cols-3 gap-5 mt-5"><Panel title="إجراءات سريعة"><div className="quick-grid">{[['customers','عميل جديد',Users],['branches','فرع جديد',MapPin],['employees','موظف جديد',UserCog],['rewards','مكافأة جديدة',Gift],['wallet','إصدار بطاقة',WalletCards],['notifications','إرسال إشعار',Send]].map(([id,l,I]:any)=><button className="quick" key={id} onClick={()=>setTab(id)}><I size={20}/>{l}</button>)}</div></Panel><Panel title="حالة النظام"><Status label="قاعدة البيانات" ok/><Status label="عزل بيانات البراندات" ok/><Status label="واجهة API" ok/><Status label="Apple Wallet" ok={rows('certificates').length>0}/></Panel><Panel title="ملخص البراند"><Info label="الفروع" value={rows('branches').length}/><Info label="الموظفون" value={rows('employees').length}/><Info label="المستويات" value={rows('tiers').length}/><Info label="المكافآت" value={rows('rewards').length}/></Panel></div></>}
 {tab==='brands'&&<div className="grid lg:grid-cols-[.75fr_1.25fr] gap-5 mt-7"><Panel title="إنشاء براند"><form onSubmit={addBrand} className="form"><Field name="name" placeholder="اسم البراند"/><Field name="slug" placeholder="brand-slug"/><button className="btn-primary"><Plus/>إنشاء وربط البراند</button></form></Panel><Panel title="كل البراندات"><Table rows={brands} columns={[['name','الاسم'],['slug','الرابط'],['is_active','الحالة']]} /></Panel></div>}
 {tab==='branches'&&<Crud title="إضافة فرع" form={<form onSubmit={e=>submit('/api/manage/branches',e,{brand_id:brand},'تمت إضافة الفرع')} className="form"><Field name="name" placeholder="اسم الفرع"/><Field name="address" placeholder="العنوان" required={false}/><button className="btn-primary"><Plus/>إضافة الفرع</button></form>} listTitle="فروع البراند" rows={rows('branches')} columns={[['name','الفرع'],['address','العنوان'],['is_active','الحالة']]}/>} 
 {tab==='customers'&&<Crud title="تسجيل عميل" form={<form onSubmit={e=>submit('/api/customers',e,{brand_id:brand},'تم تسجيل العميل وإنشاء رقم عضوية')} className="form"><Field name="name" placeholder="اسم العميل"/><Field name="phone" placeholder="رقم الهاتف"/><Field name="email" placeholder="البريد - اختياري" type="email" required={false}/><button className="btn-primary"><Plus/>إضافة العميل</button></form>} listTitle="العملاء والبطاقات" custom={<div className="list">{rows('customers').map(c=><div className="row" key={c.id}><div><b>{c.name}</b><small>{c.phone} · {c.membership_code} · {c.tier}</small></div><div className="row-actions"><span>{c.points} نقطة · {c.stamps} ختم</span><button className="small-btn" onClick={()=>adjust(c)}>+ زيارة</button><button className="small-btn" onClick={()=>issue(c)}><WalletCards size={14}/> إصدار بطاقة</button></div></div>)}</div>}/>} 
 {tab==='employees'&&<Crud title="إضافة موظف" form={<form onSubmit={e=>submit('/api/manage/employees',e,{brand_id:brand,permissions:{}},'تم إنشاء الموظف وصلاحياته')} className="form"><Field name="name" placeholder="اسم الموظف"/><Field name="email" type="email" placeholder="البريد"/><Field name="phone" placeholder="الجوال" required={false}/><select name="role" className="input"><option value="cashier">كاشير</option><option value="manager">مدير فرع</option><option value="admin">مدير البراند</option></select><select name="branch_id" className="input"><option value="">كل الفروع</option>{rows('branches').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn-primary"><Plus/>إضافة الموظف</button></form>} listTitle="الموظفون" rows={rows('employees')} columns={[['name','الاسم'],['email','البريد'],['role','الدور'],['is_active','الحالة']]}/>} 
 {tab==='tiers'&&<Crud title="إنشاء مستوى عضوية" form={<form onSubmit={e=>submit('/api/manage/tiers',e,{brand_id:brand,benefits:{}},'تم إنشاء مستوى العضوية')} className="form"><Field name="name" placeholder="ذهبي / فضي / VIP"/><Field name="rank" type="number" placeholder="الترتيب" defaultValue={rows('tiers').length+1}/><Field name="min_points" type="number" placeholder="الحد الأدنى للنقاط" defaultValue={0}/><Field name="min_spend" type="number" placeholder="الحد الأدنى للصرف" defaultValue={0}/><Field name="points_multiplier" type="number" placeholder="مضاعف النقاط" defaultValue={1}/><Field name="color" type="color" placeholder="اللون" defaultValue="#C6FF4A"/><button className="btn-primary"><Plus/>إضافة المستوى</button></form>} listTitle="ترتيب العضويات" rows={rows('tiers')} columns={[['rank','الترتيب'],['name','المستوى'],['min_points','النقاط المطلوبة'],['points_multiplier','المضاعف']]}/>} 
 {tab==='stamps'&&<Crud title="إنشاء بطاقة أختام" form={<form onSubmit={e=>submit('/api/manage/stamp-programs',e,{brand_id:brand},'تم إنشاء برنامج الأختام')} className="form"><Field name="name" placeholder="بطاقة القهوة"/><Field name="required_stamps" type="number" placeholder="عدد الأختام" defaultValue={10}/><Field name="reward_title" placeholder="المكافأة النهائية"/><select name="stamp_icon" className="input"><option value="star">نجمة</option><option value="coffee">قهوة</option><option value="heart">قلب</option><option value="check">صح</option></select><button className="btn-primary"><Plus/>إنشاء بطاقة الأختام</button></form>} listTitle="برامج الأختام" rows={rows('stamps')} columns={[['name','البرنامج'],['required_stamps','الأختام'],['reward_title','المكافأة'],['is_active','الحالة']]}/>} 
 {tab==='rewards'&&<Crud title="إضافة مكافأة" form={<form onSubmit={e=>submit('/api/manage/rewards',e,{brand_id:brand},'تمت إضافة المكافأة')} className="form"><Field name="name" placeholder="اسم المكافأة"/><Field name="description" placeholder="الوصف" required={false}/><Field name="points_cost" type="number" placeholder="تكلفة النقاط" defaultValue={100}/><Field name="stock" type="number" placeholder="الكمية - اختياري" required={false}/><Field name="image_url" placeholder="رابط الصورة - اختياري" required={false}/><button className="btn-primary"><Plus/>إضافة المكافأة</button></form>} listTitle="كتالوج المكافآت" rows={rows('rewards')} columns={[['name','المكافأة'],['points_cost','النقاط'],['stock','المخزون'],['is_active','الحالة']]}/>} 
 {tab==='wallet'&&<div className="grid xl:grid-cols-3 gap-5 mt-7"><Panel title="إعداد Apple Wallet"><form onSubmit={uploadCert} className="form"><select name="certificate_type" className="input"><option value="p12">شهادة Pass (.p12)</option><option value="pem">PEM</option><option value="wwdr">Apple WWDR</option></select><input name="file" type="file" accept=".p12,.pem,.cer" required className="input"/><button className="btn-primary"><Upload/>رفع الشهادة بأمان</button></form><div className="mt-5 text-sm muted">الشهادة تحفظ داخل Volume منفصل في السيرفر، وسجلها مرتبط بالبراند الحالي فقط.</div></Panel><Panel title="الشهادات المرفوعة"><Table rows={rows('certificates')} columns={[['filename','الملف'],['certificate_type','النوع'],['status','الحالة']]}/></Panel><Panel title="معاينة البطاقة"><div className="wallet-card" style={{background:`linear-gradient(135deg,${selected?.accent_color||'#c6ff4a'},#7aaa00)`}}><small>LOYALYN MEMBER</small><h3>{selected?.name||'بطاقة الولاء'}</h3><div className="wallet-stats"><span>النقاط<b>1,250</b></span><span>المستوى<b>ذهبي</b></span></div><div className="fake-qr">QR</div></div><p className="muted mt-4">من صفحة العملاء اضغط «إصدار بطاقة» وسيتم إنشاء رابط خاص ونسخه مباشرة.</p></Panel></div>}
 {tab==='notifications'&&<div className="grid lg:grid-cols-2 gap-5 mt-7"><Panel title="إرسال حملة"><form onSubmit={e=>submit('/api/notifications',e,{brand_id:brand,audience:'all'},'تم إنشاء حملة الإشعار')} className="form"><Field name="title" placeholder="عنوان الإشعار"/><textarea name="body" required className="input min-h-32" placeholder="نص الرسالة"/><select name="channel" className="input"><option value="in_app">داخل المنصة</option><option value="push">Push</option><option value="sms">SMS</option><option value="email">Email</option></select><button className="btn-primary"><Send/>إرسال للعملاء</button></form></Panel><Panel title="الاستهداف الذكي"><Status label="إرسال حسب البراند" ok/><Status label="حفظ صندوق إشعارات العميل" ok/><Status label="مزود Push عبر Webhook" ok/><Status label="الجدولة والحملات" ok/></Panel></div>}
 {tab==='audit'&&<div className="mt-7"><Panel title="سجل التدقيق"><Table rows={rows('audit')} columns={[['created_at','الوقت'],['action','العملية'],['entity_type','النوع'],['entity_id','المعرّف']]}/></Panel></div>}
 {tab==='settings'&&<div className="grid lg:grid-cols-2 gap-5 mt-7"><Panel title="عزل البيانات"><Status label="كل سجل مرتبط بـ brand_id" ok/><Status label="التحقق من البراند داخل API" ok/><Status label="صلاحيات حسب الدور" ok/><Status label="سجل تدقيق للتغييرات" ok/></Panel><Panel title="معلومات التشغيل"><Info label="إصدار المنصة" value="2.0.0"/><Info label="البيئة" value="Production"/><Info label="API" value="FastAPI"/><Info label="قاعدة البيانات" value="PostgreSQL 17"/></Panel></div>}
 {loading&&<div className="loading">جاري تحميل النظام...</div>}</div></Shell>
}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="glass card"><h2>{title}</h2><div className="mt-5">{children}</div></section>}
function Crud({title,form,listTitle,rows=[],columns=[],custom}:{title:string,form:React.ReactNode,listTitle:string,rows?:AnyRow[],columns?:any[],custom?:React.ReactNode}){return <div className="grid lg:grid-cols-[.72fr_1.28fr] gap-5 mt-7"><Panel title={title}>{form}</Panel><Panel title={listTitle}>{custom||<Table rows={rows} columns={columns}/>}</Panel></div>}
function Table({rows,columns}:{rows:AnyRow[],columns:any[]}){return <div className="table-wrap"><table><thead><tr>{columns.map((c:any)=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map((c:any)=><td key={c[0]}>{typeof r[c[0]]==='boolean'?(r[c[0]]?'فعال':'موقوف'):(r[c[0]]??'—')}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">لا توجد بيانات بعد</div>}</div>}
function Status({label,ok}:{label:string,ok:boolean}){return <div className="status"><span className={ok?'dot ok':'dot'}></span><b>{label}</b><small>{ok?'جاهز':'غير مكتمل'}</small></div>}
function Info({label,value}:{label:string,value:any}){return <div className="info"><span>{label}</span><b>{value}</b></div>}
